version: "2"

services:
  lint:
    image: buildkite/plugin-linter
    command: ["--id", "tapendium/aws-put-event"]
    volumes:
      - ".:/plugin:ro"

  tests:
    image: buildkite/plugin-tester
    volumes:
      - ".:/plugin:ro"

  format-shell:
    image: mvdan/shfmt
    volumes:
      - '.:/data'
    command:
      - --write
      - ./data

  lint-shell-format:
    image: mvdan/shfmt
    volumes:
      - '$PWD:/data'
    command:
      - --diff
      - ./data
