name: aws-put-event
description: Publish event to AWS event-bridge
author: https://tapendium.com
requirements:
  - aws
configuration:
  properties:
    entries:
      type: array
      minItems: 1
      contains:
        type: object
        properties:
          source:
            type: string
          resources:
            type: string
          detail:
            type: string
          detail-env:
            type: string
          detail-type:
            type: string
          event-bus-name:
            type: string
          trace-header:
            type: string
        oneOf:
          - required:
              - source
              - detail
              - detail-type
              - event-bus-name
          - required:
              - source
              - detail-env
              - detail-type
              - event-bus-name
    debug:
      type: boolean
    generate-cli-skeleton:
      type: string
    cli-input-json:
      type: string
    endpoint-id:
      type: string
    endpoint-url:
      type: string
    region:
      type: string
  required:
    - entries
  additionalProperties: false
