steps:
  - label: ":hammer: Run unit tests"
    plugins:
      docker-compose#v3.9.0:
        run: tests

  # - label: ":lint-remover: Run lint"
  #   plugins:
  #     docker-compose#v3.9.0:
  #       run: lint
