tapendium-aliases:
  merge-main: &merge-main
    seek-oss/github-merged-pr#v1.1.2:
      mode: checkout

steps:
  - label: ":hammer: Run unit tests"
    plugins:
      docker-compose#v4.3.0:
        run: tests
        # cli-version: 2

  - label: ':lint-roller: Check shell script syntax'
    plugins:
      - *merge-main
      - shellcheck#v1.3.0:
          files:
            - lib/*
            - hooks/*

  - label: ':lint-roller: Check shell script formatting'
    plugins:
      - *merge-main
      - docker-compose#v3.9.0:
          run: lint-shell-format

  - label: ":shell: Shellcheck"
    plugins:
      - seek-oss/github-merged-pr#v1.1.2:
          mode: checkout
      - shellcheck#v1.3.0:
          files:
            - "hooks/*"
            - "lib/*"
            - "tests/*"
          options: "-x"

  # - label: ":lint-remover: Run lint"
  #   plugins:
  #     docker-compose#v3.9.0:
  #       run: lint
